### ISSUE TITLE
USER STORY: Matching label size with paper size

### ISSUE THREAD

**Issue by Danpr1984** [Danpr1984/My-First-Agile-Project#2]
As a **warehouse operator** I can **select the paper size on which to print** so that **the printed label size matches the parcel size**

**Comment by Danpr1984** [comment]
In order to **share my feedback** as a **user**, I can **fill up a basic poll**

## Acceptance Criteria:

a. The option should be provided as a checkbox
b. The checkbox should be “checked” by default
c. The option should appear next to the submit button
d. After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [x] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality

**Comment by Danpr1984** [comment]
Acceptance Criteria:

a. The option should be provided as a checkbox
b. The checkbox should be “checked” by default
c. The option should appear next to the submit button
d. After submitting the default submission confirmation should be adjusted to include the user name.
